#!/usr/bin/env ruby

# Create Gemfile
gemfile_content = <<-RUBY
source "https://rubygems.org"
ruby "2.7.3"

gem "ghost_train", github: "thutterer/ghost_train", branch: "lvlup"
RUBY
File.write("Gemfile", gemfile_content)

# Bundle!
system("bundle install")

# Add app engine
system("bundle exec ghost plugin new front --mountable --skip-gemfile --skip-git --no-skip-javascript --no-full --template=https://raw.githubusercontent.com/thutterer/ghost_train/master/template.rb")

# Move engine up into root folder
system("mv front/* .; rmdir front")

# Remove unwanted files
system("rm MIT-LICENSE")

# (Hacky) Remove TODOs from gemspec
system("bundle exec ghost generate ghost foo")

# Add engine to Gemfile and rebundle
File.write("Gemfile", "gem \"front\", path: \".\"\n", mode: "a")
system("bundle install --quiet")

# Add Rakefile
rakefile_content = <<-RUBY
require 'ghost_train'
GhostTrain.call
Rails.application.load_tasks
RUBY
File.write("Rakefile", rakefile_content)

# Add Procfile
procfile_content = <<-RUBY
web: bundle exec ghost server
RUBY
File.write("Procfile", procfile_content)

# Generate logos
system("bundle exec ghost logos:generate")
